id: AC77D9F73
base_file: f44FD.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:09:51.622781
  last_modified_at: 2022-06-15 20:09:51.622788
