id: AC77D9F73
base_file: f5B69.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:09:51.625982
  last_modified_at: 2022-06-15 20:09:51.625987
